version: '3.8'

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=UTC
      - BROWSER_TIMEOUT=40000
      - MAX_TIMEOUT=60000
    ports:
      - "8191:8191"
    restart: unless-stopped
    
  wrapper:
    build: ./wrapper
    container_name: flaresolverr-wrapper
    environment:
      - FLARESOLVERR_URL=http://flaresolverr:8191
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - flaresolverr
    restart: unless-stopped
